- README.md
"happy" is a happiness index calculator built with hyperapp. It's a quite simple app, esp data-wise. But it *is* an example of an app being used in the real-world.
> Add "happy" to apps list

- README.md
Hey guys :wave:
- I've sorted all entries alphabetically as per our [contribution guidelines](https://github.com/hyperapp/awesome-hyperapp/blob/master/CONTRIBUTING.md)
- I've corrected minor spelling mistakes
Cheers
> Small corrections

- README.md
Since it's not an "app/boilerplate", and all the bullets under "resources" were docs/forums, I added a new heading I called "add-ons"
> add hyperapp-transitions

- README.md
Also, remove hyperapp-module-views which is outdated and
unmaintained
> Add hyperapp-nestable

- README.md
`hyperapp-freeze` keeps the state frozen for each action and view call, not just on load.
> Update hyperapp-freeze description ❄️

- README.md
> add moisturize dynamic HOA in utils

- README.md
Now that I have a few users and a small community building around [`hyperapp-effects`](https://github.com/okwolf/hyperapp-effects), I think it's time.
> Add hyperapp-effects

- README.md
Please consider including this link to hyperviews in the utilities section.
It's a HTML based template language that transforms to hyperscript and includes conditionals, iteration and interpolation.
It offers an alternative to JSX and raw h() calls.
It also provides capability to create hyperapp powered W3C Web Components Custom Elements.
https://github.com/davidjamesstone/hyperviews
>  Update README to include a link to hyperviews

- README.md
I'm not really sure about how the items under "Utilities" are ordered, if there is a pattern.
> add hyperapp-context

- README.md
> Update link to @hyperapp/render

- README.md
A simple example / boilerplate for working with a login form and with GraphQL
> added link for hyperapp-responsive-admin

- README.md
Hi Jorge,
I've split the Custom Elements and Template parts into two separate repos.
Please consider this change that reflects that.
Many thanks
Dave
> Split hyperviews and hyperapp-customelements

- README.md
We are creating Devtools for Hyperapp, including a time-traveling debugger. More tools will be coming in the near future.
> Add Hyperapp Devtools and time-traveling debugger mention

- README.md
Added "30-seconds-of-interviews" project to "Examples" section
> 30-seconds-of-interview

- README.md
Due I use Typescript and Parcel, I decided to create this boilerplate [joseluisq/hyperapp-starter](https://github.com/joseluisq/hyperapp-starter)
I think so it could be useful for Typescript people as starting point.
> add hyperapp-starter

- README.md
A typing practice app aiming for a simple interface. Featuring passages from the Tao Te Ching (courtesy of Project Gutenberg) and powered by Hyperapp.
cc @lukejacksonn
> add Type The Tao Te Ching to Examples

- README.md
I've added a link to a tutorial I've just published about creating a simple snake clone using Hyperapp.
> Add 'Create a Snake clone' tutorial.

- README.md
Add my hyperapp tutorial application to "Examples".
> Add https://github.com/spapas/hyperapp-tutorial

- README.md
add link to single-spa-hyperapp plugin
> Add link to single-spa-hyperapp plugin

- README.md
[Repository Search](https://github.com/ricosmall/hyperapp-search) - A simple tool for searching Github repositories.
> Add hyperapp-search

- README.md
I recently updated my old hyperapp starter. I'm very glad with the way it is, thought I might share it here!
https://github.com/loteoo/hyperapp-starter
> Add "loteoo/hyperapp-starter" starter repository

- README.md
Bit o reorg to start new lists for v2 at the top, while keeping the v1 stuff in a section at the bottom.
> new v2 lists

- README.md
Just wanted to add my styling module and walkthrough article here for V2.
> styled-components utility + 5 minute walk through for V2

- README.md
I believe it is high time we should have v2 resources, therefore I added the `V2` section also.
- [bonniss/hyparcel](https://github.com/bonniss/hyparcel) - Hyperapp v2 + TailwindCSS + Parcel boilerplate, with PurgeCSS intergrated in production.
> Fix typo & Add hyparcel - a v2 boilerplate

- README.md
[HyperMDX](https://github.com/talentlessguy/hypermdx) is a library to enhance markdown pages with Hyperapp components. The library is built on top of [Unified](https://github.com/unifiedjs/unified) and [Remark](https://github.com/remarkjs/remark/).
- components to replace HTML tags in markup
- components embedding
- sync and async support
- Remark plugins support
- custom hyperscript function support
So far there's 0 libraries for enhancing markdown with Hyperapp so I think it's worth including in the list as something that might be useful for Hyperapp developers.
> Add HyperMDX

- README.md
I updated the example to properly support v2.0.12
> Switch hyperapp-pug utility example from v1 to v2

- README.md
Hi! I updated this starter a little while back and wanted to update the description here as well to match the changes :)
> Update loteoo/hyperapp-starter description

- README.md
I found this article series really helpful (thanks @zaceno btw), and I think it should be made a bit easier to find.
> adding modular hyperapp article series

- README.md
Trying this again... I'm a noob at this please let me know if I need to do something different
> Removing message about v2 coming soon
